/**
 * Central FLUX art lookup. Reads from art-manifest.json (filesystem-derived,
 * generated by `scripts/catalog-existing-art.ts`). Falls back to procedural
 * gradients when an image is missing.
 */

import manifest from '../../art-manifest.client.json';

export type ManifestEntry = {
  key: string;
  type: string;
  character?: string;
  expression?: string;
  act?: number;
  domain?: number;
  publicUrl: string;
};

const ENTRIES = manifest.entries as ManifestEntry[];
const BY_KEY = new Map<string, ManifestEntry>(ENTRIES.map((e) => [e.key, e]));

export type NPCExpression =
  | 'neutral'
  | 'serious'
  | 'concerned'
  | 'approving'
  | 'teaching'
  | 'excited'
  | 'focused'
  | 'explaining'
  | 'defensive'
  | 'ashamed'
  | 'determined'
  | 'professional'
  | 'evasive'
  | 'calculating'
  | 'vulnerable'
  | 'resigned'
  | 'firm'
  | 'authoritative';

// Derive FLUX-available character IDs from the manifest so adding new
// portraits requires only re-running `npm run catalog:art`.
const FLUX_NPC_IDS = new Set(
  ENTRIES.filter((e) => e.type === 'character' && e.character).map((e) => e.character as string),
);

/**
 * Return the public URL for a character portrait, or null if unavailable.
 * Falls back through expressions until a known image is found.
 */
export function getCharacterPortrait(
  npcId: string | undefined | null,
  expression?: string,
): string | null {
  if (!npcId) return null;
  const id = npcId.toLowerCase();
  if (!FLUX_NPC_IDS.has(id)) return null;

  const candidates = [expression, 'neutral'].filter(Boolean) as string[];
  for (const expr of candidates) {
    const entry = BY_KEY.get(`npc_${id}_${expr}`);
    if (entry?.publicUrl) return entry.publicUrl;
  }
  // Last resort: any portrait for this character
  const any = ENTRIES.find((e) => e.character === id && e.type === 'character');
  return any?.publicUrl ?? null;
}

/**
 * Background variant pools by act number. Multiple scenes in the same act get
 * different backgrounds via deterministic rotation on scene order.
 */
const ACT_BG_POOLS: Record<number, string[]> = {
  1: ['bg_act1_hq_day', 'bg_act1_war_room', 'bg_act1_office_lobby', 'bg_act1_hq_night'],
  2: ['bg_act2_london_hq_lobby', 'bg_act2_london_office', 'bg_act2_data_center'],
  3: ['bg_act3_munich_exterior', 'bg_act3_munich_lab', 'bg_act3_crypto_lab', 'bg_act3_server_physical'],
  4: ['bg_act4_singapore_dc_exterior', 'bg_act4_singapore_dc_interior', 'bg_act4_noc', 'bg_act4_cable_room'],
  5: ['bg_act5_ny_financial', 'bg_act5_interview_room', 'bg_act5_access_logs'],
  6: ['bg_act6_sentinel_lab', 'bg_act6_assessment_results', 'bg_act6_cloud_abstract'],
  7: ['bg_act7_tokyo_soc', 'bg_act7_forensics_lab', 'bg_act7_tokyo_exterior'],
  8: ['bg_act8_sf_office', 'bg_act8_code_review', 'bg_act8_git_history'],
};

/**
 * Returns a public URL for the scene background. Strategy:
 *   1. If sceneId matches a known pattern (d{N}a{M}s{X}), use act-based pool with order rotation.
 *   2. If domain+act provided, use act pool.
 *   3. Otherwise null (caller renders gradient).
 */
export function getSceneArt(opts: {
  sceneId?: string;
  domain?: number;
  act?: number;
  sceneOrder?: number;
}): string | null {
  let act = opts.act;
  let order = opts.sceneOrder;

  if (!act && opts.sceneId) {
    // Match "dN-sNN" (V2 flat) or "dNaMsX" (V1 act-based)
    const v2 = opts.sceneId.match(/^d(\d+)-s(\d+)/);
    const v1 = opts.sceneId.match(/^d(\d+)a(\d+)s(\d+)$/);
    if (v2) {
      act = parseInt(v2[1], 10);   // domain → act pool 1-to-1
      order = order ?? parseInt(v2[2], 10);
    } else if (v1) {
      act = parseInt(v1[2], 10);
      order = order ?? parseInt(v1[3], 10);
    }
  }

  // Walk the pool starting from the rotated index until a valid manifest
  // entry is found, so a missing key never breaks the scene background.
  const pickFromPool = (pool: string[], anchor: number): string | null => {
    for (let i = 0; i < pool.length; i++) {
      const entry = BY_KEY.get(pool[(anchor + i) % pool.length]);
      if (entry?.publicUrl) return entry.publicUrl;
    }
    return null;
  };

  if (act && ACT_BG_POOLS[act]?.length) {
    const pool = ACT_BG_POOLS[act];
    const idx = (((order ?? 1) - 1) % pool.length + pool.length) % pool.length;
    const url = pickFromPool(pool, idx);
    if (url) return url;
  }

  // Domain-based fallback (domain N maps 1:1 to act-N pool). Rotate when an
  // order is provided so V1 scenes (which lack a structured sceneId) still
  // cycle through variants instead of locking to pool[0].
  if (opts.domain && ACT_BG_POOLS[opts.domain]?.length) {
    const pool = ACT_BG_POOLS[opts.domain];
    const idx = (((order ?? 1) - 1) % pool.length + pool.length) % pool.length;
    return pickFromPool(pool, idx);
  }

  return null;
}

export function getDiagramArt(key: string): string | null {
  const entry = BY_KEY.get(key) ?? BY_KEY.get(`diagram_${key}`);
  return entry?.publicUrl ?? null;
}

export function getEvidenceArt(key: string): string | null {
  const entry = BY_KEY.get(key) ?? BY_KEY.get(`evidence_${key}`);
  return entry?.publicUrl ?? null;
}

export function getUiArt(key: string): string | null {
  const entry = BY_KEY.get(key) ?? BY_KEY.get(`ui_${key}`);
  return entry?.publicUrl ?? null;
}

/**
 * Domain gradient fallback. Used when no scene art is available.
 */
const DOMAIN_GRADIENTS: Record<number, string> = {
  1: 'linear-gradient(135deg, #050b1a 0%, #0a1428 35%, #06b6d422 70%, #050b1a 100%)',
  2: 'linear-gradient(135deg, #050b1a 0%, #1a1428 35%, #8b5cf622 70%, #050b1a 100%)',
  3: 'linear-gradient(135deg, #050b1a 0%, #0a1a1a 35%, #10b98122 70%, #050b1a 100%)',
  4: 'linear-gradient(135deg, #050b1a 0%, #1a0a28 35%, #ec489922 70%, #050b1a 100%)',
  5: 'linear-gradient(135deg, #050b1a 0%, #0a0a28 35%, #f59e0b22 70%, #050b1a 100%)',
  6: 'linear-gradient(135deg, #050b1a 0%, #040a14 35%, #a855f722 70%, #050b1a 100%)',
  7: 'linear-gradient(135deg, #050b1a 0%, #28091a 35%, #ef444422 70%, #050b1a 100%)',
  8: 'linear-gradient(135deg, #050b1a 0%, #0d1a2d 35%, #06b6d422 70%, #050b1a 100%)',
};

export function getDomainGradient(domain: number | undefined | null): string {
  if (!domain) return DOMAIN_GRADIENTS[1];
  return DOMAIN_GRADIENTS[domain] ?? DOMAIN_GRADIENTS[1];
}

/**
 * Domain accent (used for borders, glow, badges).
 */
const DOMAIN_ACCENT: Record<number, string> = {
  1: '#06b6d4',
  2: '#8b5cf6',
  3: '#10b981',
  4: '#ec4899',
  5: '#f59e0b',
  6: '#a855f7',
  7: '#ef4444',
  8: '#14b8a6', // teal — distinct from D1 cyan; mirrors --domain-8
};

export function getDomainAccent(domain: number | undefined | null): string {
  if (!domain) return DOMAIN_ACCENT[1];
  return DOMAIN_ACCENT[domain] ?? DOMAIN_ACCENT[1];
}

/**
 * Ken Burns subtle zoom keyframes for Framer Motion.
 * Slow drift: 12s, alternating between sceneIndex parities to vary direction.
 */
export function kenBurnsForScene(sceneIndex: number) {
  const variant = sceneIndex % 4;
  switch (variant) {
    case 0:
      return { scale: [1.04, 1.12], x: ['-1%', '1%'], y: ['0%', '-1%'] };
    case 1:
      return { scale: [1.12, 1.04], x: ['1%', '-1%'], y: ['-1%', '0%'] };
    case 2:
      return { scale: [1.06, 1.14], x: ['0%', '-1%'], y: ['1%', '-1%'] };
    default:
      return { scale: [1.14, 1.06], x: ['-1%', '0%'], y: ['-1%', '1%'] };
  }
}

export function getManifestStats() {
  return {
    total: ENTRIES.length,
    byType: manifest.totals.byType,
    byCharacter: manifest.totals.byCharacter,
    byAct: manifest.totals.byAct,
  };
}
