INSERT INTO cat_questions (
  domain_id, topic_cluster, question_text, options, correct_index,
  explanation, mnemonic_hint, cognitive_level, question_type,
  difficulty_rating, irt_a, irt_b, irt_c, source, is_active
) VALUES
(
  5,
  'biometrics',
  'A biometric system manufacturer claims their device has a CER of 0.5%. A competing device has a CER of 2.1%. Which statement BEST describes the comparison?',
  '["The device with CER 2.1% is more accurate because higher CER means fewer total errors", "The device with CER 0.5% is more accurate because lower CER indicates better performance at the point where FRR equals FAR", "Both devices are equally accurate because CER only indicates the calibration point, not overall accuracy", "Neither CER value is meaningful without knowing the individual FRR and FAR rates at different sensitivity settings"]'::jsonb,
  1,
  'The Crossover Error Rate (CER), also called Equal Error Rate (EER), is the point where the False Rejection Rate equals the False Acceptance Rate. A lower CER indicates a more accurate biometric device. The device with 0.5% CER has better overall accuracy than the device with 2.1% CER. CER is the standard metric for comparing biometric device accuracy.',
  'Lower CER = better biometric. CER is where FRR crosses FAR. Think: lower crossover = fewer errors.',
  'understand',
  'best_answer',
  'medium',
  1.00, 0.00, 0.20,
  'ai_generated', true
),
(
  5,
  'credential_attacks',
  'Your SIEM alerts on unusual Kerberos activity: hundreds of service ticket requests from a single workstation for service accounts across multiple servers, all within a few minutes. The requesting user account has no business need for these services. What is the FIRST action to contain this likely Kerberoasting attack?',
  '["Reset the passwords for all service accounts in the domain", "Deploy network segmentation to isolate the affected workstation", "Disable the compromised user account and isolate the workstation from the network", "Implement AES-256 encryption for all Kerberos service tickets"]'::jsonb,
  2,
  'Kerberoasting involves requesting many service tickets to crack offline. The FIRST containment action is to disable the compromised account and isolate the workstation to stop the ticket harvesting. Resetting all service account passwords is a remediation step but not the first action. Network segmentation and encryption improvements are longer-term preventive measures.',
  'Kerberoasting = mass service ticket requests for offline cracking. FIRST = stop the harvesting by disabling and isolating.',
  'apply',
  'first_action',
  'medium',
  1.50, 0.60, 0.20,
  'ai_generated', true
),
(
  5,
  'access_control_models',
  'A network administrator configures a firewall with the following rules: allow HTTP from the internal network to the internet, allow HTTPS from the internal network to the internet, deny all other traffic. These rules apply equally to all users regardless of identity. Which access control model does this firewall configuration BEST represent?',
  '["Discretionary Access Control because the administrator chose which traffic to allow", "Mandatory Access Control because the firewall labels are enforced by the system", "Attribute-Based Access Control because the rules evaluate traffic attributes", "Rule-Based Access Control because global rules are applied equally to all subjects"]'::jsonb,
  3,
  'Firewalls are the classic example of Rule-Based Access Control. Rules are applied globally and equally to all traffic regardless of user identity. The rules are based on protocol, port, and direction rather than individual user permissions or classification labels. While the admin configured the rules (discretion), the model itself is rule-based because rules apply uniformly.',
  'Firewalls = Rule-Based. Rules apply to ALL traffic equally. Implicit deny at the end.',
  'understand',
  'most_likely',
  'medium',
  1.10, 0.10, 0.22,
  'ai_generated', true
),
(
  5,
  'mfa',
  'An organization wants to implement phishing-resistant multifactor authentication for all employees. Several employees have recently fallen victim to phishing attacks where they entered their credentials and SMS one-time passwords on fake login pages. Which solution BEST addresses this requirement?',
  '["FIDO2-compliant hardware security keys that use public key cryptography bound to the legitimate site origin", "Time-based one-time passwords generated by a mobile authenticator application", "Push notifications sent to registered mobile devices requiring user approval", "Email-based one-time passwords sent to the employee''s corporate email address"]'::jsonb,
  0,
  'FIDO2/WebAuthn hardware security keys are phishing-resistant because they cryptographically bind authentication to the legitimate site''s origin. Even if a user visits a phishing site, the key will not authenticate because the origin does not match. TOTP, push notifications, and email OTPs can all be intercepted through real-time phishing proxies.',
  'FIDO2 = phishing-resistant because the key is bound to the site origin. Fake site = wrong origin = no authentication.',
  'remember',
  'best_answer',
  'medium',
  0.80, -0.50, 0.20,
  'ai_generated', true
),
(
  5,
  'identity_lifecycle',
  'A large enterprise discovers through an audit that 15% of active user accounts belong to employees who left the organization over the past two years. The accounts were never disabled because the HR system was not integrated with the identity management platform. What is the root cause of this failure?',
  '["Lack of multifactor authentication on the identity management platform", "Absence of automated deprovisioning triggered by HR system events such as employee termination", "Insufficient password complexity requirements allowing accounts to remain active", "Missing access control lists on the identity management platform''s configuration"]'::jsonb,
  1,
  'The root cause is the lack of automated deprovisioning integration between the HR system and the identity management platform. When HR processes a termination, it should automatically trigger account disabling in the identity system. Without this integration, manual processes are relied upon, and accounts inevitably slip through the cracks. MFA and password policies do not address deprovisioning.',
  'HR termination should auto-trigger account disabling. Manual deprovisioning = guaranteed orphan accounts.',
  'analyze',
  'scenario',
  'medium',
  1.70, 0.80, 0.20,
  'ai_generated', true
)
ON CONFLICT (question_text) DO NOTHING;