-- =============================================================================
-- CISSP Quest -- Library Topics: Domain 5 (Identity and Access Management)
-- Topics: 5.3.1 through 5.7.1
-- Source basis: ISC2 CBK, NIST SP 800-63B (authentication), NIST SP 800-162 (ABAC),
--               NIST SP 800-207 (Zero Trust), RFC 4120 (Kerberos), RFC 6749 (OAuth 2.0),
--               SAML 2.0 specification, and public-domain cybersecurity knowledge.
-- Generated: 2026-04-16
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 5.3.1 Authentication Factors and MFA
-- ---------------------------------------------------------------------------
INSERT INTO library_topics (
  domain_id, topic_number, title, one_liner, content_markdown,
  key_formulas, comparison_table, exam_tips, think_like_manager,
  memory_hack, memory_anchor
) VALUES (
  5,
  '5.3.1',
  'Authentication Factors and MFA',
  'Authentication is based on five factor types (something you know, have, are, do, and where you are); MFA requires two or more distinct factor types; biometric performance is measured by FAR, FRR, and CER — with lower CER indicating better biometric system quality.',
  '## Authentication Factors and MFA

Authentication is the process of verifying that a claimant is who they claim to be — distinguishing genuine users from impostors. Authentication factors are the categories of evidence a claimant presents. NIST SP 800-63B (Digital Identity Guidelines: Authentication and Lifecycle Management) is the authoritative U.S. government framework for authentication requirements.

### The Five Authentication Factor Types

**Type 1 — Something You Know**: Knowledge factors — passwords, PINs, passphrases, challenge questions, and lock combinations. The most common and also the weakest authentication factor because knowledge can be shared, guessed, phished, or stolen without physical theft. NIST SP 800-63B discourages complexity requirements, mandatory rotation without evidence of compromise, and maximum password length limits (all of which produce counterproductive behavior). It recommends checking passwords against known-breached password lists.

**Type 2 — Something You Have**: Possession factors — hardware tokens (RSA SecurID, YubiKey), smart cards, mobile devices (receiving an SMS OTP or push notification), and cryptographic authenticators. Possession factors are stronger than knowledge factors because stealing one requires physical access or device compromise. A one-time password (OTP) generated by a hardware token uses TOTP (Time-based OTP, RFC 6238) or HOTP (HMAC-based OTP, RFC 4226) algorithms.

**Type 3 — Something You Are**: Inherence factors — biometrics. Fingerprints, iris scans, facial recognition, voice recognition, hand geometry. Biometrics are unique to the individual but have important limitations: they cannot be changed if compromised (you cannot issue a new fingerprint), they are probabilistic rather than deterministic (biometric matching works on similarity scores, not exact matches), and they may be defeated by spoofing attacks (fake fingerprints, printed photos).

**Type 4 — Something You Do**: Behavioral factors — gait analysis, typing rhythm (keystroke dynamics), signature dynamics, voice behavioral patterns. Less commonly implemented but used in continuous authentication scenarios and behavioral biometrics for fraud detection.

**Type 5 — Somewhere You Are**: Location factors — physical location (verified by GPS or premises-based sensors), network location (IP geolocation, corporate network access). Location factors are often used as contextual authentication signals rather than standalone factors (logging in from an unusual country triggers additional challenges).

### Multi-Factor Authentication

**MFA (Multi-Factor Authentication)** requires successful authentication using factors from two or more distinct factor categories. A password plus an SMS OTP is MFA (Type 1 + Type 2). A password plus a security question is NOT MFA — both are Type 1 (something you know). NIST SP 800-63B defines three Authentication Assurance Levels (AALs):

- **AAL1**: Single-factor authentication (password alone)
- **AAL2**: Two-factor authentication (one factor must be a cryptographic authenticator)
- **AAL3**: Phishing-resistant hardware cryptographic authenticator (FIDO2/WebAuthn, smart card with PIN) — provides the strongest assurance

### Biometric Performance Metrics

Biometric systems match an individual''s presented biometric trait against a stored reference. Because matching is probabilistic, two error rates are defined:

**FAR (False Acceptance Rate)**: The rate at which the system incorrectly accepts an unauthorized individual (type II error, false positive). A high FAR means impostors get through. Reducing FAR requires raising the matching threshold (requiring closer similarity).

**FRR (False Rejection Rate)**: The rate at which the system incorrectly rejects an authorized individual (type I error, false negative). A high FRR means legitimate users are denied access. Reducing FRR requires lowering the matching threshold (accepting lower similarity scores).

**CER (Crossover Error Rate)**: Also called the Equal Error Rate (EER), the point at which FAR and FRR are equal. CER is the standard metric for comparing biometric system quality — a lower CER indicates a more accurate system because it achieves the crossover point with lower error rates. When FAR is reduced by raising the threshold, FRR increases proportionally, and vice versa. The CER is the intersection of these two curves.',
  '[{"formula":"CER = point where FAR = FRR","description":"Crossover Error Rate — lower CER means better biometric accuracy; used to compare biometric system quality"}]'::jsonb,
  '{"headers": ["Factor Type", "Category", "Examples", "Strength", "Primary Vulnerability"], "rows": [["Type 1", "Something You Know", "Password, PIN, passphrase, security question", "Low-Medium", "Phishing, guessing, credential stuffing, sharing"], ["Type 2", "Something You Have", "Hardware token, smart card, TOTP app, YubiKey, SMS OTP (weakest)", "Medium-High", "Device theft; SIM swapping for SMS"], ["Type 3", "Something You Are", "Fingerprint, iris, facial recognition, voice", "Medium-High", "Biometric spoofing; cannot be revoked if compromised"], ["Type 4", "Something You Do", "Gait, typing rhythm, behavioral biometrics", "Medium", "Behavioral mimicry; changes with injury/fatigue"], ["Type 5", "Somewhere You Are", "GPS location, corporate network, IP geolocation", "Low-Medium (contextual)", "VPN spoofing; corporate network does not prove identity"]]}'::jsonb,
  'Authentication exam areas: (1) MFA = two or more DIFFERENT factor types — two passwords is NOT MFA. (2) Know all five factor types and examples of each. (3) Biometrics: FAR = accepts impostors (security risk); FRR = rejects authorized users (availability risk); CER = the comparison metric (lower = better). (4) NIST AAL levels: AAL1 = 1 factor, AAL2 = 2 factors (one cryptographic), AAL3 = hardware phishing-resistant. (5) SMS OTP is Type 2 but is the weakest possession factor (SIM swap attacks). FIDO2/WebAuthn (hardware key) is the strongest.',
  'As a manager, MFA is the single highest-ROI security control you can implement. Statistics consistently show that MFA prevents over 99% of automated credential stuffing attacks. The practical challenge is adoption and usability: friction in MFA leads to workarounds. Choose MFA methods that match your user population — push notification apps (Authenticator, Duo) have much higher adoption than hardware tokens for knowledge workers. For privileged accounts, hardware security keys (FIDO2/WebAuthn) should be mandatory regardless of convenience cost.',
  'KHADS — Know (Type 1), Have (Type 2), Are (Type 3), Do (Type 4), Somewhere (Type 5). Or: "Knowledge, Hardware, Anatomy, Dynamics, Site." MFA = Mix At least two Factor types (not two of the same). CER = the crossing point on the biometric curve — lower is better. FAR = impostors accepted (security failure). FRR = legitimate users rejected (availability failure).',
  'In the London Office, the security operations center access panel requires three factors: a typed passphrase (Type 1), a FIDO2 hardware key tap (Type 2), and a fingerprint scan (Type 3). The biometric scanner report on the wall shows FAR at 0.001% and FRR at 0.8%, with a CER of 0.4% — the security team considers this acceptable for the access sensitivity. Down the hall, the general office WiFi uses only a password (Type 1 only — AAL1). The privileged access workstation requires Type 1 + Type 3 hardware key — AAL3.'
);

-- ---------------------------------------------------------------------------
-- 5.4.1 Kerberos Protocol
-- ---------------------------------------------------------------------------
INSERT INTO library_topics (
  domain_id, topic_number, title, one_liner, content_markdown,
  key_formulas, comparison_table, exam_tips, think_like_manager,
  memory_hack, memory_anchor
) VALUES (
  5,
  '5.4.1',
  'Kerberos Protocol',
  'Kerberos is a symmetric-key authentication protocol using a trusted third party (KDC) to issue time-limited tickets — authenticating users once and providing ticket-based access to multiple services without re-entering credentials, while pass-the-ticket and golden ticket attacks target the Kerberos ticket infrastructure.',
  '## Kerberos Protocol

Kerberos (RFC 4120) is a network authentication protocol designed for open, potentially hostile networks. It uses symmetric key cryptography and a trusted third party — the Key Distribution Center (KDC) — to authenticate clients and services without sending passwords over the network. Kerberos is the primary authentication protocol in Microsoft Active Directory environments and is widely used in Kerberos-aware enterprise applications.

### Kerberos Architecture

**KDC (Key Distribution Center)**: The trusted third party, consisting of two logical components:

- **AS (Authentication Service)**: Authenticates the user initially and issues a Ticket-Granting Ticket (TGT).
- **TGS (Ticket-Granting Service)**: Issues service tickets (also called session tickets) to allow access to specific services.

**Principal**: Any entity in the Kerberos system — a user, a service, or a host — identified by a Kerberos principal name (e.g., user@REALM or host/server.example.com@REALM).

**Realm**: The Kerberos administrative domain (analogous to an Active Directory domain). Cross-realm authentication allows tickets from one realm to be trusted by another (inter-domain or inter-forest trust in Active Directory terms).

### Kerberos Authentication Flow

1. **AS Exchange**: The client sends an AS_REQ to the Authentication Service, requesting a TGT (typically identifying themselves and the TGS service they want a ticket for). The AS verifies the client''s identity (by attempting to decrypt a component encrypted with the user''s key derived from their password). The AS returns an AS_REP containing a **TGT** (encrypted with the KDC''s secret key — the client cannot read it) and a **TGS session key** (encrypted with the client''s key — the client CAN read it). The client decrypts the TGS session key using their password-derived key.

2. **TGS Exchange**: The client sends a TGS_REQ to the Ticket-Granting Service, presenting the TGT and an authenticator (timestamp encrypted with the TGS session key) to request a service ticket for a specific service. The TGS verifies the TGT (which it can decrypt because it holds the KDC key) and the authenticator''s timestamp (replay prevention). The TGS returns a TGS_REP containing a **service ticket** (encrypted with the service''s key) and a **service session key** (encrypted with the TGS session key).

3. **AP Exchange**: The client presents the service ticket and a fresh authenticator (encrypted with the service session key) to the target service (AP_REQ). The service decrypts the service ticket using its own key (which it shares with the KDC), extracts the service session key, and uses it to decrypt and verify the authenticator. The service may optionally send back a mutual authentication message (AP_REP) proving it could decrypt the service ticket.

### Key Properties

**Single Sign-On (SSO)**: After the initial AS exchange, the TGT is used to obtain service tickets for multiple services without re-entering the password. The user authenticates once per logon session.

**No password transmitted**: The password never travels over the network. The KDC verifies identity by testing whether the client can decrypt something encrypted with the password-derived key.

**Time-based**: Kerberos tickets include timestamps and lifetimes. All Kerberos systems must be time-synchronized (within five minutes by default). Clock skew outside this window causes authentication failures. NTP synchronization is a Kerberos operational requirement.

**Replay protection**: Authenticators include timestamps; the KDC/service rejects any authenticator that has been seen before or whose timestamp falls outside the acceptable skew window.

### Kerberos Attacks

**Pass-the-Ticket (PtT)**: An attacker who captures a valid TGT or service ticket from memory (using tools like Mimikatz to extract tickets from LSASS process memory on Windows) can use the stolen ticket to authenticate as the victim without knowing their password.

**Golden Ticket Attack**: If an attacker compromises the KRBTGT account (the KDC''s own service account in Active Directory, whose password is used to encrypt TGTs), they can forge TGTs for any user in the domain, with any privilege, for any lifetime. A forged TGT is called a golden ticket. Recovery requires resetting the KRBTGT account password twice (because the KDC keeps the previous password for backward compatibility).

**Silver Ticket Attack**: If an attacker compromises a service account''s NTLM hash, they can forge service tickets for that specific service without going through the KDC. Silver tickets do not require domain admin compromise but are limited to the compromised service.',
  NULL,
  '{"headers": ["Component/Term", "Description", "Analogy"], "rows": [["KDC", "Trusted third party — issues tickets", "The passport office"], ["AS (Authentication Service)", "Verifies identity; issues TGT", "The identity verification desk"], ["TGT (Ticket-Granting Ticket)", "Proof that AS authenticated you; presented to TGS for service tickets", "Your passport (proves who you are to ticket agents)"], ["TGS (Ticket-Granting Service)", "Issues service tickets upon presentation of valid TGT", "The gate agent who checks your passport and issues boarding passes"], ["Service Ticket", "Authorizes access to a specific service", "The boarding pass (valid only for one flight)"], ["Authenticator", "Timestamped proof you currently hold the session key (anti-replay)", "The QR code scan that expires in 5 minutes"], ["Realm", "Kerberos administrative domain", "The country issuing the passport"]]}'::jsonb,
  'Kerberos exam areas: (1) KDC = AS + TGS. AS issues TGT. TGS issues service tickets. (2) Passwords never travel over the network. (3) Clock skew > 5 minutes = authentication failure (NTP required). (4) Pass-the-ticket = steal ticket from memory (Mimikatz). Golden ticket = forge TGTs after compromising KRBTGT. (5) TGT is encrypted with KDC''s key (client cannot read it). Service ticket is encrypted with the service''s key (service reads it; client cannot). (6) Kerberos provides SSO — one authentication, multiple service tickets.',
  'As a manager, Active Directory environments are Kerberos environments. The KRBTGT account is the most sensitive account in your Active Directory domain — its compromise is the highest-impact AD attack. Protect it through: least privilege on domain controllers, monitoring for unusual TGT requests, limiting delegation, and having a documented KRBTGT password reset procedure ready to execute (reset twice, spaced 10 hours apart to allow replication). Monitor for pass-the-ticket indicators: logons from unusual hosts using existing tickets.',
  'KDC = Key Distribution Center: the Kerberos airport. AS issues your Passport (TGT). TGS issues Boarding Passes (service tickets). You use your passport to get boarding passes; you use boarding passes to board planes (access services). Passwords never leave your laptop — you just prove you know your PIN. Clock skew = passport expired — keep NTP synchronized. Golden Ticket = forged passport — happens when the passport printer (KRBTGT) is stolen.',
  'In the London Office identity management room, a Kerberos flow diagram fills the wall. Step 1: the analyst types their password at the workstation — AS verifies identity, returns a TGT (the analyst''s "passport" for the day). Step 2: the analyst opens the file server application — the TGS is contacted with the TGT, returns a service ticket (boarding pass for the file server). Step 3: the file server checks the ticket, grants access. The analyst never typed a password for the file server. On the threat board: a red alert for a pass-the-ticket attack detected last week — Mimikatz extracted a TGT from a compromised workstation; the KRBTGT password was reset twice as a precaution.'
);

-- ---------------------------------------------------------------------------
-- 5.5.1 Federated Identity
-- ---------------------------------------------------------------------------
INSERT INTO library_topics (
  domain_id, topic_number, title, one_liner, content_markdown,
  key_formulas, comparison_table, exam_tips, think_like_manager,
  memory_hack, memory_anchor
) VALUES (
  5,
  '5.5.1',
  'Federated Identity',
  'Federated identity allows users authenticated by one organization (Identity Provider) to access services at another (Service Provider) using standards-based assertions — SAML 2.0 for enterprise SSO, OAuth 2.0 for API authorization, and OpenID Connect for consumer identity — without sharing credentials across boundaries.',
  '## Federated Identity

Federated identity is a system that allows a user''s identity and authentication to be recognized and trusted across organizational boundaries without the service provider needing to manage the user''s credentials. The Identity Provider (IdP) authenticates the user and asserts their identity; the Service Provider (SP) trusts the IdP''s assertion and grants access. Federated identity is the foundation of enterprise Single Sign-On (SSO) across cloud services and partner organizations.

### SAML 2.0 (Security Assertion Markup Language)

SAML 2.0 (OASIS standard, 2005) is the dominant enterprise standard for federated SSO. It uses XML-based security assertions that the IdP generates and the SP validates. SAML 2.0 defines three assertion types:

- **Authentication assertions**: "This user was authenticated at time X using method Y"
- **Attribute assertions**: "This user has these attributes (role, department, email)"
- **Authorization decision assertions**: "This user is (or is not) authorized to access resource Z"

**SAML SP-Initiated Flow (most common)**:
1. User tries to access the SP (e.g., Salesforce).
2. SP has no session — redirects user to the IdP with an AuthnRequest.
3. User authenticates at the IdP (e.g., corporate Azure AD).
4. IdP generates a digitally signed SAML assertion, redirects user back to the SP with the assertion.
5. SP validates the assertion signature, creates a session, grants access.

**SAML IdP-Initiated Flow**:
1. User authenticates at the IdP.
2. IdP provides a portal of available SPs.
3. User selects an SP — IdP generates and sends the assertion directly.

SAML 2.0 uses XML digital signatures for assertion integrity and authenticity. The IdP''s signing certificate must be registered with the SP out-of-band for trust to be established.

### OAuth 2.0 (Authorization Framework)

OAuth 2.0 (RFC 6749) is an authorization framework — not an authentication protocol. OAuth 2.0 allows a resource owner (user) to grant a third-party application (client) limited access to a protected resource (API) without sharing their credentials. The user authenticates to an Authorization Server (typically operated by the resource provider or IdP) and grants the client an **access token** with defined scope and lifetime.

OAuth 2.0 defines several authorization grant flows:
- **Authorization Code Flow**: Most secure for web applications — access token exchanged on server side, not exposed to browser.
- **Authorization Code + PKCE**: Recommended for mobile and single-page apps — code challenge prevents authorization code interception.
- **Client Credentials Flow**: Machine-to-machine (no user involved) — client authenticates directly with credentials.

OAuth 2.0 is commonly confused with an authentication protocol, but it only answers "what can this client do?" not "who is this user?" OpenID Connect solves this gap.

### OpenID Connect (OIDC)

OpenID Connect is an identity layer built on top of OAuth 2.0 (standardized 2014). It adds an **ID Token** (a JWT — JSON Web Token) that contains claims about the authenticated user (sub, name, email, etc.) alongside the OAuth 2.0 access token. OIDC answers "who is this user?" which OAuth 2.0 alone cannot. OIDC is the consumer identity standard used by Google Sign-In, Apple Sign In, Microsoft identity platform, and most modern SSO implementations.

**Key distinction**: Use SAML 2.0 for enterprise SSO (browser-based, XML assertions). Use OIDC/OAuth 2.0 for API-based and mobile applications (JSON tokens).

### WS-Federation

WS-Federation (WS-Fed) is a Microsoft-ecosystem federation standard predating SAML 2.0, still used in Windows-integrated environments (Active Directory Federation Services / ADFS). WS-Fed is being gradually replaced by SAML 2.0 and OIDC in modern deployments.',
  NULL,
  '{"headers": ["Standard", "Purpose", "Token Format", "Use Case", "Assertion/Token Type"], "rows": [["SAML 2.0", "Authentication + attribute assertions (SSO)", "XML assertions, signed with X.509 certificate", "Enterprise SSO to cloud SaaS (Salesforce, ServiceNow, Workday)", "Authentication + Attribute + AuthorizationDecision assertions"], ["OAuth 2.0", "Authorization (API access delegation)", "Access token (opaque or JWT)", "API access, third-party app authorization (\"Sign in with Google\" API scope)", "Access token (scope-limited, time-limited)"], ["OpenID Connect", "Authentication (identity) built on OAuth 2.0", "ID Token (JWT) + Access Token", "Consumer identity, modern web/mobile SSO", "ID token with user claims (sub, name, email, etc.)"], ["WS-Federation", "Authentication (legacy enterprise SSO)", "XML tokens (Security Tokens)", "Windows/ADFS legacy integration", "Security Token Service (STS) tokens"]]}'::jsonb,
  'Federated identity exam areas: (1) SAML = enterprise SSO (XML, IdP/SP, browser redirects). (2) OAuth 2.0 = authorization (API delegation) — NOT authentication. (3) OIDC = authentication built on OAuth 2.0 (adds ID token with user claims). (4) OAuth 2.0 access tokens prove "what you can do"; OIDC ID tokens prove "who you are." (5) SP-initiated vs IdP-initiated SAML flow — know both directions. (6) SAML assertions are signed with the IdP''s certificate; SP must have the IdP''s public key registered to validate signatures.',
  'As a manager, federated identity is how your organization enables SSO to cloud services (Microsoft 365, Salesforce, ServiceNow, Workday) without managing separate credentials for each. Your IdP (Azure AD, Okta, Ping Identity) becomes the central authentication hub. The critical governance question is: who controls which apps users can access through federation? Ensure your IdP configuration includes conditional access policies (require MFA for high-sensitivity apps, block access from untrusted locations) rather than providing uncontrolled SSO to every app.',
  'SAML = Security Assertion Markup Language = enterprise SSO (XML envelope). OAuth = Open Authorization = here is your API access token (not an ID). OIDC = OAuth + "Who Are You?" (adds ID token). Remember: OAuth answers "what can this app do?" OIDC answers "who is this person?". WS-Fed = Windows SSO (legacy, ADFS). Federated = trust the other school''s ID card.',
  'In the London Office, the IAM dashboard shows three federation flows active simultaneously. The SAML 2.0 flow handles Salesforce SSO — a user authenticates to Azure AD, which issues a signed XML assertion that Salesforce validates (enterprise SSO). The OAuth 2.0 flow handles the corporate mobile app accessing the API — a service account gets an access token with scoped permissions. The OIDC flow handles the customer portal — users sign in with Google, the ID token with their email and name is validated, and a customer session is created. Three protocols, three purposes, one identity infrastructure.'
);

-- ---------------------------------------------------------------------------
-- 5.6.1 Access Control Models
-- ---------------------------------------------------------------------------
INSERT INTO library_topics (
  domain_id, topic_number, title, one_liner, content_markdown,
  key_formulas, comparison_table, exam_tips, think_like_manager,
  memory_hack, memory_anchor
) VALUES (
  5,
  '5.6.1',
  'Access Control Models',
  'MAC enforces system-wide classification labels centrally; DAC lets resource owners grant permissions; RBAC assigns permissions to roles rather than individuals; ABAC uses policy rules combining multiple attributes — with RBAC being the enterprise default and ABAC the most granular and flexible.',
  '## Access Control Models

Access control models define who can access what resources and under what conditions. The choice of access control model has fundamental implications for how permissions are granted, managed, and revoked. NIST SP 800-162 provides guidance on Attribute-Based Access Control, and NIST RBAC model guidelines are foundational to most enterprise implementations.

### MAC: Mandatory Access Control

In **Mandatory Access Control**, access decisions are made by the system based on security labels attached to both subjects (users/processes) and objects (data/resources), according to a policy that users cannot override. A subject can only access an object if the system''s security policy permits the combination of the subject''s clearance and the object''s classification label.

MAC is **mandatory** because no individual user or resource owner can grant access that the policy does not permit — the policy is enforced centrally and cannot be overridden. MAC is used in high-security government and military environments where strict need-to-know must be enforced regardless of individual user decisions. The Bell-LaPadula model (no read up, no write down) is the theoretical basis for MAC in classified systems. Modern MAC implementations include SELinux and AppArmor on Linux, which enforce mandatory policies on process and file access.

### DAC: Discretionary Access Control

In **Discretionary Access Control**, the resource owner (the user who created or owns a resource) has discretion over who else can access it and what permissions they have. The classic example is a standard file system: the file creator sets read, write, and execute permissions for owner, group, and others (Unix/Linux permission model), or uses Access Control Lists (ACLs) to grant specific permissions to specific users (Windows NTFS). If the owner wants to grant a colleague access, they can do so without central authorization.

DAC is flexible and intuitive — resource owners manage their own data. Its weakness is that it is susceptible to Trojan horse attacks: a malicious program running as a user inherits all of that user''s permissions, including permissions to all files the user has DAC access to.

### RBAC: Role-Based Access Control

In **Role-Based Access Control**, permissions are assigned to roles rather than to individual users, and users are assigned to roles. A user''s effective access is the sum of permissions from all roles assigned to them. RBAC simplifies permission management enormously in large organizations: when a new employee joins the security operations team, they are added to the "SOC Analyst" role rather than having individual permissions configured. When their role changes, removing them from the role removes all associated permissions simultaneously.

NIST RBAC model (ANSI/INCITS 359-2004) defines four levels: Flat RBAC (basic user-role-permission assignment), Hierarchical RBAC (roles inherit from parent roles, e.g., "Senior Analyst" inherits all "Analyst" permissions), Constrained RBAC (adds separation of duty constraints — no user can be assigned to roles that would conflict), and Symmetric RBAC (full permissions management through roles).

RBAC is the dominant model in enterprise IT — Active Directory security groups, cloud IAM roles (AWS IAM, Azure RBAC), and enterprise applications all implement RBAC.

### ABAC: Attribute-Based Access Control

**Attribute-Based Access Control** makes access decisions based on policy rules that evaluate multiple attributes simultaneously: subject attributes (role, department, clearance level, training completion), object attributes (classification, sensitivity, data owner, creation date), environmental attributes (time of day, network location, authentication strength), and action (read, write, delete). ABAC is the most flexible and granular access control model — it can express access policies like "users in the Finance department with a SOX training completion certificate may modify budget records during business hours from corporate network IP ranges."

ABAC uses a policy decision point (PDP) that evaluates the policy rules and a policy enforcement point (PEP) that enforces the PDP''s decision. The XACML (eXtensible Access Control Markup Language) standard defines an XML-based policy language for ABAC. Cloud IAM systems increasingly support ABAC through tag-based policies and conditions. NIST SP 800-162 provides guidance on ABAC implementation.',
  NULL,
  '{"headers": ["Model", "Who Decides Access?", "Policy Flexibility", "Scalability", "Trojan Horse Resistance", "Primary Use Case"], "rows": [["MAC", "System enforces centrally; users cannot override", "Low (system policy fixed by administrators)", "Good (policy applies uniformly)", "High (policy enforced regardless of user action)", "Government/military classified systems, high-assurance OS (SELinux)"], ["DAC", "Resource owner grants permissions", "High (owner has full discretion)", "Poor (ad hoc permissions proliferate)", "Low (malware inherits user''s permissions)", "Standard OS file systems; small-scale resource sharing"], ["RBAC", "Administrators assign roles; roles have permissions", "Medium (role definitions controlled by admins)", "Good (one role change affects all members)", "Medium (roles reduce granular permission proliferation)", "Enterprise IT (Active Directory groups, cloud IAM roles, ERP access)"], ["ABAC", "Policy rules evaluate multiple attributes dynamically", "Very High (fine-grained, context-aware policies)", "Complex to manage; good at scale with automation", "High (context conditions limit exposure)", "Zero Trust architectures, cloud-native IAM, microservices access control"]]}'::jsonb,
  'Access control model exam areas: (1) MAC = system-enforced, security labels, no user override (government/military). (2) DAC = owner decides (flexible, Trojan horse risk). (3) RBAC = roles hold permissions; users get roles (enterprise standard). (4) ABAC = attributes + policy rules (most flexible, most granular). (5) The classic trap: "Discretionary" means the owner has discretion — not that it is optional. (6) MAC requires lattice-based labels (Bell-LaPadula compatible). RBAC supports separation of duty constraints in constrained RBAC.',
  'As a manager, RBAC should be the default model for enterprise access management. The practical benefit is reviewability: during an access review or audit, you review roles and their members rather than individual permissions for every user. When an employee changes departments, a role change propagates immediately. The failure mode of RBAC is role explosion — organizations that create one role per person have implemented DAC with extra steps. Establish role governance: define roles by function, not by individual, and review role membership quarterly.',
  'MDRА — Mandatory (centrally enforced labels), Discretionary (owner decides), Role-based (roles hold permissions, users get roles), Attribute-based (policy evaluates multiple attributes). Ascending flexibility and granularity: MAC (rigid) → DAC (owner''s choice) → RBAC (role-organized) → ABAC (any attribute, any policy). Think of MAC as the military officer who cannot share classified docs regardless of what the general says. DAC = your Google Drive file, your choice. RBAC = job title = access level. ABAC = multiple factors evaluated per request.',
  'In the London Office IAM room, four access control systems are shown on the architecture diagram. The classified document vault uses MAC (SELinux enforces security labels — not even the vault administrator can move a Top Secret file to an Unclassified share). The old HR file server uses DAC (each manager owns their team''s folder and controls access manually — a mess of ad-hoc permissions). The ERP system uses RBAC (Finance Analyst role, Finance Manager role, AP Clerk role — adding a new employee assigns them to their role). The new cloud data platform uses ABAC (a policy: "if subject.department=Finance AND object.classification<=Confidential AND time=BusinessHours AND location=CorporateNetwork, PERMIT READ").'
);

-- ---------------------------------------------------------------------------
-- 5.7.1 Privileged Access Management
-- ---------------------------------------------------------------------------
INSERT INTO library_topics (
  domain_id, topic_number, title, one_liner, content_markdown,
  key_formulas, comparison_table, exam_tips, think_like_manager,
  memory_hack, memory_anchor
) VALUES (
  5,
  '5.7.1',
  'Privileged Access Management',
  'PAM protects high-value accounts (admins, service accounts, root) through credential vaulting, just-in-time access provisioning, session recording, and continuous monitoring — limiting the blast radius of privileged credential compromise, which is the primary enabler of advanced persistent threats.',
  '## Privileged Access Management

Privileged Access Management (PAM) is the security discipline focused on controlling, monitoring, and auditing privileged accounts — accounts with elevated permissions that, if compromised, provide significant leverage to an attacker. Privileged accounts include system administrators (local admin, Domain Admin, root), service accounts (accounts used by applications and automated processes), network device accounts, database accounts (DBA, sa), and cloud service accounts. The compromise of a single privileged account is the most common precursor to significant data breaches and ransomware attacks.

### Why Privileged Accounts Are High-Value Targets

A standard user account compromise is serious but limited in scope — the attacker gains access to what that user can access. A privileged account compromise can give the attacker control over entire systems, the ability to disable security controls, access to credential stores, and the ability to move laterally across the network with minimal friction. MITRE ATT&CK documents privilege escalation and credential access as two of the most impactful attack techniques, and PAM controls directly mitigate both.

### Credential Vaulting

A **privileged credential vault** (or password vault) stores privileged account credentials encrypted in a centralized, access-controlled repository. Users and applications retrieve credentials from the vault through an authenticated, authorized request rather than knowing (or storing) the credential themselves. Vaults provide:

- **Credential rotation**: Automated password changes on a schedule or after each use, ensuring credentials are never static and are automatically revoked after checked-in
- **Check-out/check-in workflow**: Users check out a credential for a session, the vault records who accessed it and when, and the credential is rotated upon check-in
- **Break-glass accounts**: Emergency accounts with credentials in the vault, accessible only through a documented break-glass process with full audit trail
- **Application-to-application password management**: Service accounts whose passwords are managed by the vault, eliminating hardcoded credentials in application configuration files

### Just-In-Time (JIT) Access

**Just-In-Time access** (also called time-limited privilege elevation or ephemeral access) provides privileged permissions only for the duration of a specific approved task, rather than assigning standing privileges. A systems administrator who needs to restart a production service receives temporary elevated permissions for that specific task, automatically expiring after a defined time window or task completion. JIT access implements the principle of least privilege at a temporal level: even trusted administrators do not have standing administrative access that could be exploited if their account is compromised between tasks.

Microsoft''s Privileged Identity Management (PIM) in Azure Active Directory implements JIT access for cloud resources. CyberArk, BeyondTrust, and Delinea are leading enterprise PAM platforms with JIT capabilities.

### Session Recording and Monitoring

PAM solutions record all privileged sessions — every command typed, every screen interaction, every file accessed — creating an immutable audit trail of all privileged activity. Session recordings serve multiple purposes: forensic investigation (what did the attacker do after compromising the admin account?), compliance (evidence that privileged access was used appropriately for SOX, PCI DSS, HIPAA audits), and deterrence (administrators who know their sessions are recorded are less likely to take unauthorized actions).

Real-time session monitoring allows security operations to detect and terminate anomalous privileged sessions in progress — an administrator who suddenly starts deleting large volumes of files or exporting database dumps can be cut off before the damage is complete.

### Service Account Management

Service accounts represent a significant PAM challenge because they often have broad permissions (applications need access to many resources), their passwords are rarely rotated (because the rotation would break the application), they are not associated with a specific person (so ownership and oversight are unclear), and they are difficult to enforce MFA on. Best practices for service account PAM include: managed service accounts (domain-joined accounts whose passwords are managed automatically by Active Directory), application identity frameworks (OAuth 2.0 client credentials with short-lived tokens), and vault-managed service account passwords with automated rotation.',
  NULL,
  '{"headers": ["PAM Capability", "What It Does", "Risk It Mitigates", "Example Implementation"], "rows": [["Credential Vaulting", "Stores privileged credentials encrypted; controls access to them", "Credential theft (hardcoded passwords, password sharing)", "CyberArk Vault, BeyondTrust, HashiCorp Vault"], ["Just-In-Time Access", "Grants elevated privileges for defined task window only; revokes automatically", "Standing privilege compromise (attacker uses always-on admin rights)", "Azure AD PIM, CyberArk EPM, BeyondTrust"], ["Session Recording", "Records all commands and screen activity during privileged sessions", "Insider threat; forensic gaps; compliance (SOX, PCI DSS)", "CyberArk PSM, BeyondTrust Session Manager"], ["Credential Rotation", "Automatically changes privileged account passwords on schedule or post-use", "Credential reuse; long-lived static credentials", "Automated rotation in CyberArk, AWS Secrets Manager"], ["Service Account Management", "Manages non-human credentials with vaulting and rotation", "Hardcoded passwords in apps; stale service accounts", "Managed Service Accounts (AD), HashiCorp Vault dynamic secrets"]]}'::jsonb,
  'PAM exam areas: (1) PAM controls the "privileged" tier of accounts — domain admins, root, service accounts, network device credentials. (2) Credential vaulting prevents hardcoded and shared passwords. (3) JIT access = least privilege at the temporal level — no standing admin rights. (4) Session recording provides forensic audit trail of all privileged actions. (5) The exam may present a scenario where an attacker pivots using admin credentials — PAM controls (JIT + vaulting) are the answer. Know that PAM directly counters lateral movement and privilege escalation attack techniques.',
  'As a manager, PAM is non-negotiable for any organization with meaningful IT infrastructure. The data is consistent: privileged credential abuse is the most common thread in advanced persistent threat and ransomware incidents. The business case for PAM is not theoretical — calculate the cost of a domain admin credential being compromised and used to encrypt every server with ransomware versus the cost of a PAM deployment. Operationally, the biggest PAM implementation challenge is service accounts — the buried hardcoded credentials in applications that have not been touched in years. Fund a service account inventory and PAM integration as a foundational project.',
  'PAM = Protecting Admin Might: Vault the credentials (lock them up), JIT the access (time-limit it), Record the session (film everything), Rotate the passwords (change the locks after every use). The most dangerous account in your environment is not the one with the most permissions — it is the one with the most permissions that nobody is watching. PAM watches it.',
  'In the London Office privileged access workstation room, every admin session is controlled. To access a production database, the DBA opens the PAM portal, requests JIT access to the database admin role (approved within 2 minutes by their manager), and retrieves a time-limited credential from the vault. The session is recorded — every SQL query logged. After 2 hours, access automatically expires and the credential is rotated. The session recording goes into the compliance archive. On the threat board: a PAM alert from last month shows an anomalous session that exfiltrated the role definition — the session was terminated after 90 seconds, the credential rotated immediately, and the attacker found themselves locked out before completing the exfiltration.'
);
